name: Generate Docs

on:
  push:
    branches: [main]
    paths:
      - "packages/**"
      - "docs/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "typedoc.json"
      - ".github/workflows/docs.yml"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm docs:build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
